language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: Lint, FrontendTest, BackendTest, Build
      name: Lint
      script:
        - npm install
        - npm run lint
    - name: FrontendTest
      script:
        - npm install
        - npm run test
    - name: BackendTest
      script:
        - cd server
        - npm install
        - npm run test
    - name: Build
      script:
        - npm run build
branches:
  only:
    - master
    - tests
